### ISSUE TITLE
NullPointerException on v1.0.2

### ISSUE THREAD

**Issue by niczm25** [ayltai/Android-Lib-reCAPTCHA#11]
> java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                   at android.lib.recaptcha.ReCaptcha$1.handleMessage(ReCaptcha.java:385)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

An error occurred when network connection is lost during fetching of image. Using the method below.

` reCaptcha.showChallengeAsync(myRecaptchaPublicKey, this);`

**Comment by niczm25** [comment]
Unnecessary issue. please ignore, i will have just to use the current version.

**Comment by arielkl9** [comment]
man use the correct version
good luck
